layer_config:
    load_weights:
        - image_encoder
        - mask_downsample
        - memory_attention
        - memory_encoder
        - sam_prompt_encoder
        - sam_mask_decoder
        - obj_ptr_proj
        - obj_ptr_tpos_proj
    train_layers:
        - sam_mask_decoder
        - fuser
        - sparse_lemb0
        - sparse_lemb1
        - dense_lemb0
        - dense_lemb1
