from configs.default import _CN as cfg

PREPROCESSED_BASE_DIR = '/data/nfs/lhj/DenseMatching/MegaDepth/covis_mask_box_pair_info'
PREPROCESSED_LIST_DIR = 'data'

cfg.DATASET.TRAINVAL_DATA_SOURCE = "MegaDepth"
cfg.DATASET.TRAIN_DATA_ROOT = "/data/nfs/lhj/DenseMatching/MegaDepth"
cfg.DATASET.TRAIN_NPZ_ROOT = PREPROCESSED_BASE_DIR
cfg.DATASET.TRAIN_LIST_PATH = f"{PREPROCESSED_LIST_DIR}/train_processed_list.txt"
cfg.DATASET.MIN_OVERLAP_SCORE_TRAIN = 0.0

cfg.DATASET.TEST_DATA_SOURCE = "MegaDepth"
cfg.DATASET.VAL_DATA_ROOT = cfg.DATASET.TEST_DATA_ROOT = "/data/nfs/lhj/DenseMatching/MegaDepth"
cfg.DATASET.VAL_NPZ_ROOT = PREPROCESSED_BASE_DIR
cfg.DATASET.VAL_LIST_PATH = f"{PREPROCESSED_LIST_DIR}/val_processed_list.txt"
cfg.DATASET.TEST_NPZ_ROOT = PREPROCESSED_BASE_DIR
cfg.DATASET.TEST_LIST_PATH = f"{PREPROCESSED_LIST_DIR}/test_processed_list.txt"
cfg.DATASET.MIN_OVERLAP_SCORE_TEST = 0.0

cfg.DATASET.MGDPT_IMG_RESIZE = 1024
cfg.DATASET.MGDPT_IMG_PAD = True
cfg.DATASET.MGDPT_DF = 8

# cfg.TRAINER.N_SAMPLES_PER_SUBSET = 2
cfg.TRAINER.N_SAMPLES_PER_SUBSET = 100
cfg.TRAINER.DATA_SAMPLER = 'distributed'
cfg.TRAINER.SEED = 42
cfg.TRAINER.ADAMW_DECAY = 0.05
# cfg.TRAINER.MSLR_MILESTONES = [30, 35, 40]
cfg.TRAINER.MSLR_MILESTONES = [30, 40, 50]
# cfg.TRAINER.MSLR_MILESTONES = [60]
cfg.TRAINER.MSLR_GAMMA = 0.3
cfg.TRAINER.WARMUP_TYPE = 'linear'
cfg.TRAINER.WARMUP_EPOCHS = 5
cfg.TRAINER.WARMUP_STEP = 0
cfg.TRAINER.WARMUP_RATIO = 0.01
cfg.TRAINER.GRADIENT_CLIPPING = 0.5
cfg.TRAINER.FT_LR_SCALE = 1.0

cfg.TRAINER.VIS_INTERVAL = 50
