python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher loftr --direct --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher NN --extractor d2net-ss --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher NN --extractor landmark --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher NN --extractor disk-desc --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher NN --extractor r2d2-desc --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher NN --extractor context-desc --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher NN --extractor superpoint_aachen --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher superglue_disk --extractor disk-desc --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_500_g --matcher superglue_outdoor --extractor superpoint_aachen --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4

python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_500.txt --output_dir outputs/eval_v --matcher superglue_outdoor --extractor superpoint_aachen --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4 --viz
python3 evaluation.py --input_dir /data/nfs/lhj/DenseMatching/MegaDepth --input_pairs ./data/megadepth_mr.txt --output_dir outputs/eval_mr --matcher superglue_outdoor --extractor superpoint_aachen --resize 1024 --save --overlaper samatcher --mask_filter --mask_filter_thresh 0.4 --viz_box_mask_constraint