accelerate launch --config_file configs/accelerate_config.yaml --num_processes 4 train.py \
    --data_cfg_path configs/train_config.py \
    --exp_name SAMatcher \
    --batch_size 12 \
    --val_batch_size 12 \
    --num_workers 8 \
    --true_lr 3e-4 \
    --num_epochs 50 \
    --log_every_n_steps 5 \
    --output_dir outputs \
    --mixed_precision no \
    --wandb_offline